### ISSUE TITLE
Bug - Cocoapods 

### ISSUE THREAD

**Issue by warmachinesocial** [LibrePass/LibrePass-iOS#2]
Just cloned the repo and was trying it out however you're using pods for dependency manager, I would like to ask if at this stage we're even using any? Like could have gone with swift package manager?

**Comment by aeoliux** [comment]
To use swiftpm I would need to manually add SignalArgon2 to the app, which is available only on CocoaPods.

I'm not going to write my own Argon2 library or switch to another one, so I won't add swiftpm management. I am sorry

**Comment by warmachinesocial** [comment]
No worries I'm also learning ios development. Now I see its just a wrapper because its written in C. I had similar situation with hex3 library.

Though I see there's an alternative to it. 
https://github.com/tmthecoder/Argon2Swift

I will try to learn about pods because I haven't touch it.

**Comment by warmachinesocial** [comment]
I get signing issue have you dealt with this?

**Comment by aeoliux** [comment]
Literally all you need is to do:
1. Open terminal and get cocoapods (use google)
2. `cd` into project directory
3. run `pod install`

I don't see any issues here.

**Comment by warmachinesocial** [comment]
Thanks got done with that part
