### ISSUE TITLE
Feature Request: QR Code Scanning for TOTP Setup

### ISSUE THREAD

**Issue by OmarNazzal150** [LibrePass/LibrePass-iOS#8]
Dear LibrePass Team,

I hope this message finds you well. First of all, thank you for developing and maintaining the LibrePass password manager—an essential tool for security-conscious users like myself.

I’ve been using LibrePass and appreciate its commitment to open-source transparency and end-to-end encryption. However, I’ve noticed that the current TOTP setup process involves manual entry of secret keys. As someone who values both security and efficiency, I find this method time-consuming and prone to errors.

My suggestion is to introduce QR code scanning support for TOTP setup within the LibrePass iOS app. QR codes would allow users to effortlessly import TOTP secrets, streamlining the process and reducing the risk of mistakes.

By implementing QR code scanning, LibrePass can enhance user experience and encourage more people to adopt strong authentication practices. I believe this feature would be highly beneficial for the community.

Thank you for considering my request. Keep up the excellent work, and I look forward to seeing LibrePass continue to evolve!

Best regards,

**Comment by aeoliux** [comment]
Hi, I haven't implemented it yet, because I didn't have a real iOS device to test it. Now I bought one, so give me some time. It shouldn't take so long.

**Comment by aeoliux** [comment]
@OmarNazzal150 done :)

**Comment by OmarNazzal150** [comment]
Good. But I have a question. When librepass is coming to the app store.

**Comment by aeoliux** [comment]
Probably never. You need to compile LibrePass using Xcode or sideload .ipa using either SideStore, AltStore or other similar tools.

**Comment by OmarNazzal150** [comment]
Oh! Come on, bro! Okay, fine. I will close this issue as completed as done

**Comment by aeoliux** [comment]
@OmarNazzal150 everyone can publish this app on the AppStore, if there are no changes made in the src or the fork is open source. But I won't. I'm not going to pay apple tax just to publish this app in the AppStore. I prefer more "independent" ways to distribute apps. Really sorry.

**Comment by OmarNazzal150** [comment]
Okay. Bye.
